export const ROLES = ["ADMIN", "DRIVER", "USER"] as const;

export type PublicRole = (typeof ROLES)[number];

export const SELF_SERVE_ROLES = ["DRIVER", "USER"] as const;

export const OTP_LENGTH = 6;

export const AUTH_ERROR = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  ACCOUNT_NOT_VERIFIED: "ACCOUNT_NOT_VERIFIED",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_BLOCKED: "ACCOUNT_BLOCKED",
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  OTP_MAX_ATTEMPTS: "OTP_MAX_ATTEMPTS",
  OTP_COOLDOWN: "OTP_COOLDOWN",
  OTP_UNAVAILABLE: "OTP_UNAVAILABLE",
} as const;
